# -*- coding: utf-8 -*-
"""Desafio Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2bF8olt46LLVl40ZPtO85sYpZwtT9d1

# **Desafio de Análise de Dados: "O que influencia o desempenho acadêmico dos estudantes?"**


**Contexto**: Você é uma cientista de dados contratada por uma universidade interessada em entender quais fatores do cotidiano dos alunos estão mais relacionados ao desempenho nas provas finais. A instituição deseja usar esses insights para desenvolver políticas de apoio estudantil.

# 1. Análise Exploratória dos Dados (EDA)

### a) Qual a distribuição de notas (exam_score) entre os alunos?
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/student_habits_performance.csv')

df.head()

print(df['exam_score'].describe())

plt.figure(figsize=(10, 6))
sns.histplot(df['exam_score'], kde=True, bins=20)
plt.title('Distribuição das notas (exam_score)')
plt.xlabel('Nota do Exame')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()

"""### b) Há diferença de desempenho entre gêneros?"""

plt.figure(figsize=(8, 6))
sns.boxplot(x='gender', y='exam_score', data=df, palette='pastel')
plt.title('Distribuição das Notas por Gênero')
plt.xlabel('Gênero')
plt.ylabel('Nota no Exame')
plt.grid(True)
plt.show()

df.groupby('gender')['exam_score'].agg(['mean', 'std', 'count'])

"""### c) Existe correlação entre horas de estudo e nota final? E entre horas em redes sociais/Netflix e nota?

"""

correlacoes = df[['study_hours_per_day', 'social_media_hours', 'netflix_hours', 'exam_score']].corr()
print(correlacoes['exam_score'].sort_values(ascending=False))

sns.scatterplot(x='study_hours_per_day', y='exam_score', data=df)
plt.title('Horas de Estudo vs Nota no Exame')
plt.xlabel('Horas de Estudo por Dia')
plt.ylabel('Nota no Exame')
plt.grid(True)
plt.show()

sns.scatterplot(x='social_media_hours', y='exam_score', data=df)
plt.title('Horas em Redes Sociais vs Nota no Exame')
plt.xlabel('Horas em Redes Sociais por Dia')
plt.ylabel('Nota no Exame')
plt.grid(True)
plt.show()

sns.scatterplot(x='netflix_hours', y='exam_score', data=df)
plt.title('Horas Assistindo Netflix vs Nota no Exame')
plt.xlabel('Horas de Netflix por Dia')
plt.ylabel('Nota no Exame')
plt.grid(True)
plt.show()

# Tamanho da figura e estilo
plt.figure(figsize=(18, 5))  # Largura, altura

# 1. Horas de Estudo vs Nota
plt.subplot(1, 3, 1)
sns.scatterplot(x='study_hours_per_day', y='exam_score', data=df)
plt.title('Horas de Estudo vs Nota')
plt.xlabel('Horas de Estudo por Dia')
plt.ylabel('Nota no Exame')
plt.grid(True)

# 2. Redes Sociais vs Nota
plt.subplot(1, 3, 2)
sns.scatterplot(x='social_media_hours', y='exam_score', data=df)
plt.title('Redes Sociais vs Nota')
plt.xlabel('Horas em Redes Sociais')
plt.ylabel('')
plt.grid(True)

# 3. Netflix vs Nota
plt.subplot(1, 3, 3)
sns.scatterplot(x='netflix_hours', y='exam_score', data=df)
plt.title('Netflix vs Nota')
plt.xlabel('Horas Assistindo Netflix')
plt.ylabel('')
plt.grid(True)

# Exibir os três gráficos juntos
plt.tight_layout()
plt.show()

"""1. Correlação entre study_hours_per_day e exam_score: 0.825
Força da correlação: Muito forte (acima de 0.8).

Sinal: Positivo → quanto mais horas o aluno estuda por dia, maior tende a ser sua nota no exame.

Interpretação: Existe uma forte relação positiva entre o tempo dedicado ao estudo e o desempenho. Isso sugere que estudar mais está fortemente associado a melhores notas.

2. Correlação entre social_media_hours e exam_score: -0.166
Força da correlação: Fraca.

Sinal: Negativo → quanto mais tempo gasto em redes sociais, ligeiramente menor tende a ser a nota.

Interpretação: Há uma fraca relação negativa, o que indica que passar mais tempo em redes sociais pode estar modestamente associado a notas um pouco mais baixas, mas o efeito não é muito forte.

3. Correlação entre netflix_hours e exam_score: -0.172
Força da correlação: Fraca.

Sinal: Negativo.

Interpretação: Assim como redes sociais, há uma fraca correlação negativa — ou seja, assistir mais Netflix pode estar levemente relacionado a piores notas, mas o impacto não é expressivo por si só.

### d) Como a variável saúde mental está impactando a nota final dos alunos.
"""

correlacao = df['mental_health_rating'].corr(df['exam_score'])
print(f"Correlação entre saúde mental e nota final: {correlacao:.2f}")

df.groupby('mental_health_rating')['exam_score'].mean().plot(kind='bar', figsize=(8,5), color='skyblue')
plt.title('Nota Média por Avaliação de Saúde Mental')
plt.xlabel('Avaliação de Saúde Mental')
plt.ylabel('Nota Média no Exame')
plt.grid(axis='y')
plt.show()

"""# 2. Investigação de Correlações e Tendências

### a) Quais hábitos têm maior correlação com alto desempenho (nota ≥ 85)?
"""

df.columns

# 3. Criar coluna de alto desempenho (nota >= 85)
df['Alto_Desempenho'] = df['exam_score'] >= 85

# 4. Converter coluna booleana para inteiro (True = 1, False = 0)
df['Alto_Desempenho'] = df['Alto_Desempenho'].astype(int)

# 5. Selecionar apenas colunas numéricas (excluindo 'Nota' se necessário)
colunas_numericas = df.select_dtypes(include=['int64', 'float64']).drop(columns=['exam_score'], errors='ignore')

# 6. Calcular correlação com alto desempenho
correlacoes = colunas_numericas.corr()['Alto_Desempenho'].drop('Alto_Desempenho').sort_values(ascending=False)

# 7. Exibir as correlações
print("\n🧠 Correlação dos hábitos com alto desempenho (≥ 85):\n")
print(correlacoes)

# 8. Visualização com gráfico de barras
plt.figure(figsize=(10, 6))
sns.barplot(x=correlacoes.values, y=correlacoes.index, palette='coolwarm')
plt.title('Correlação dos Hábitos com Alto Desempenho (Nota ≥ 85)')
plt.xlabel('Coeficiente de Correlação')
plt.tight_layout()
plt.show()

"""### b) Como o nível de educação dos pais influencia a nota?"""

import matplotlib.pyplot as plt
from scipy.stats import f_oneway
# Verificar os valores únicos da coluna (ajuste o nome conforme necessário)
print("Níveis de educação dos pais:")
print(df['parental_education_level'].unique())

# Agrupar pela escolaridade dos pais e calcular média da nota
media_por_educacao = df.groupby('parental_education_level')['exam_score'].mean().sort_values(ascending=False)

print("\n📊 Média de notas por nível de escolaridade dos pais:\n")
print(media_por_educacao)

# Gráfico de barras
plt.figure(figsize=(10, 6))
sns.barplot(x=media_por_educacao.values, y=media_por_educacao.index, palette='viridis')
plt.xlabel('Média da Nota')
plt.ylabel('Nível de Educação dos Pais')
plt.title('Influência da Escolaridade dos Pais na Nota')
plt.tight_layout()
plt.show()

# Teste ANOVA - diferença significativa entre os grupos?
grupos = [grupo['exam_score'].values for nome, grupo in df.groupby('parental_education_level')]
anova = f_oneway(*grupos)
print(f"\n📈 Resultado do teste ANOVA: p-valor = {anova.pvalue:.4f}")
if anova.pvalue < 0.05:
    print("→ Diferenças significativas entre os grupos de escolaridade dos pais.")
else:
    print("→ Não há diferenças estatisticamente significativas entre os grupos.")

df['parental_education_level'].value_counts()

df.groupby('parental_education_level')['exam_score'].mean().sort_values(ascending=False)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.barplot(x='parental_education_level', y='exam_score', data=df, ci=None, order=df['parental_education_level'].value_counts().index)
plt.title('Nota Média por Nível de Educação dos Pais')
plt.xlabel('Nível de Educação dos Pais')
plt.ylabel('Nota Média no Exame')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### c) Alunos com empregos de meio período têm desempenho diferente?"""

df.columns

# Verificar os valores únicos
print("Valores possíveis:", df['part_time_job'].unique())

#  Calcular média das notas por grupo
media_por_grupo = df.groupby('part_time_job')['exam_score'].mean()
print("\nMédia da Nota por grupo (com/sem emprego):\n", media_por_grupo)

#  Gráfico de barras
plt.figure(figsize=(6, 4))
sns.barplot(data=df, x='part_time_job', y='exam_score', palette='Set2')
plt.title('Notas por Situação de Emprego de Meio Período')
plt.xlabel('Tem Emprego de Meio Período')
plt.ylabel('Nota Média (exam_score)')
plt.tight_layout()
plt.show()

# Teste t de Student
grupo_com_emprego = df[df['part_time_job'] == 'Yes']['exam_score']
grupo_sem_emprego = df[df['part_time_job'] == 'No']['exam_score']
t_stat, p_valor = ttest_ind(grupo_com_emprego, grupo_sem_emprego)

print(f"\n📊 Teste t de Student: p-valor = {p_valor:.4f}")
if p_valor < 0.05:
    print("→ Diferença significativa nas notas entre quem tem e quem não tem emprego.")
else:
    print("→ Não há diferença significativa nas notas entre os grupos.")

df['part_time_job'].value_counts()

df.groupby('part_time_job')['exam_score'].mean()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.boxplot(x='part_time_job', y='exam_score', data=df)
plt.title('Desempenho no Exame x Emprego de Meio Período')
plt.xlabel('Emprego de Meio Período (0=Não, 1=Sim)')
plt.ylabel('Nota no Exame')
plt.grid(True)
plt.show()

from scipy.stats import ttest_ind

grupo_trabalha = df[df['part_time_job'] == 1]['exam_score']
grupo_nao_trabalha = df[df['part_time_job'] == 0]['exam_score']

t_stat, p_value = ttest_ind(grupo_trabalha, grupo_nao_trabalha, equal_var=False)
print(f"T-statística = {t_stat:.2f}, p-valor = {p_value:.4f}")

"""O p-valor (0.3946) é bem maior que 0.05, o que indica que não há evidência estatística suficiente para afirmar que o desempenho (nota no exame) dos alunos com emprego de meio período é diferente do dos alunos sem emprego.

A t-estatística negativa sugere que a média dos alunos que trabalham é um pouco menor, mas essa diferença não é significativa estatisticamente.

alunos com emprego de meio período não apresentam diferença significativa no desempenho acadêmico em comparação com alunos que não trabalham.

# 3. Modelagem Preditiva Construa um modelo de regressão para prever a exam_score com base nas demais variáveis.
Avalie a importância de cada variável no modelo. Separe em variáveis que possuem impacto negativo e positivo no score do exame.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns

# ===  Pré-processamento ===
# Remover coluna que não contribui para o modelo
df_model = df.drop(columns=["student_id"])

# Codificar variáveis categóricas com get_dummies
df_encoded = pd.get_dummies(df_model, drop_first=True)

# Separar variável alvo e preditoras
X = df_encoded.drop(columns=["exam_score"])
y = df_encoded["exam_score"]

# ===  Separar em treino e teste ===
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ===  Treinar modelos ===
lr_model = LinearRegression()
rf_model = RandomForestRegressor(random_state=42)

lr_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

# ===  Avaliação dos modelos ===
y_pred_lr = lr_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)

r2_lr = r2_score(y_test, y_pred_lr)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"R² Regressão Linear: {r2_lr:.3f}")
print(f"R² Random Forest: {r2_rf:.3f}")

# === Importância das variáveis ===

# Regressão Linear: coeficientes
coef_lr = pd.Series(lr_model.coef_, index=X.columns).sort_values()
print("\nCoeficientes - Regressão Linear:")
print(coef_lr)

# Separar impacto positivo e negativo
coef_positivo = coef_lr[coef_lr > 0]
coef_negativo = coef_lr[coef_lr < 0]

# Random Forest: importância
importances_rf = pd.Series(rf_model.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nTop 10 Importâncias - Random Forest:")
print(importances_rf.head(10))

# ===  Visualização ===

# Gráfico dos coeficientes positivos e negativos
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
coef_positivo.plot(kind='barh', color='green')
plt.title('Impacto Positivo no Exam Score (Reg. Linear)')

plt.subplot(1, 2, 2)
coef_negativo.plot(kind='barh', color='red')
plt.title('Impacto Negativo no Exam Score (Reg. Linear)')
plt.tight_layout()
plt.show()

# Gráfico da importância das variáveis no Random Forest
plt.figure(figsize=(10, 6))
sns.barplot(x=importances_rf.head(10), y=importances_rf.head(10).index, palette='viridis')
plt.title("Top 10 Importâncias - Random Forest")
plt.xlabel("Importância")
plt.ylabel("Variável")
plt.show()

"""# 4. Recomendações Com base nas análises, sugira pelo menos 3 ações práticas que a universidade pode implementar para melhorar o desempenho acadêmico dos alunos.

**Criar Programas de Acompanhamento e Planejamento de Estudos**

Justificativa: A variável com maior impacto positivo foi study_hours_per_day, com coeficiente +9.53.

Ação sugerida:

Implementar mentorias acadêmicas ou grupos de estudo assistidos por monitores.

Oferecer oficinas de planejamento de tempo e técnicas de estudo eficazes.

Criar metas personalizadas de estudo por curso ou matéria.

**Promover Hábitos de Sono Saudáveis e Saúde Mental**

Justificativa:

sleep_hours (+1.98) e mental_health_rating (+1.96) influenciam fortemente o desempenho.

Ação sugerida:

Parcerias com especialistas para oferecer palestras sobre sono, ansiedade e bem-estar.

Disponibilizar sessões com psicólogos ou terapeutas estudantis.

Criar campanhas educativas sobre higiene do sono e equilíbrio emocional.

**Educar sobre o Uso Consciente de Redes Sociais e Streaming**

Justificativa:

Horas gastas em social_media_hours (−2.69) e netflix_hours (−2.32) impactam negativamente.

Ação sugerida:

Campanhas de “detox digital” e uso consciente de telas.

Oficinas que ajudem os alunos a identificar distrações digitais.

Incentivar o uso de apps de foco como Forest, Pomodoro, ou funcionalidades de tempo de tela.

**Estimular mais horas de estudo diárias:**

Alunos com mais de X horas/dia tiveram notas significativamente maiores.

Reduzir o tempo gasto em redes sociais/Netflix:

Correlação negativa entre tempo em mídias e exam_score.

Oferecer suporte à saúde mental:

Alunos com boas avaliações de saúde mental tiveram melhor desempenho.

Programa de incentivo ao exercício físico:

Frequência de exercício correlaciona positivamente com nota.
"""